# Install dependencies

In [ ]:
!pip install opencv-python-headless
!pip install opencv-python==3.4.2.17
!pip install opencv-contrib-python==3.4.2.17

     |████████████████████████████████| 47.6 MB 35 kB/s 
     |████████████████████████████████| 25.0 MB 109 kB/s 
  Attempting uninstall: opencv-python
    Found existing installation: opencv-python 4.1.2.30
    Uninstalling opencv-python-4.1.2.30:
      Successfully uninstalled opencv-python-4.1.2.30
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.
     |████████████████████████████████| 30.6 MB 27 kB/s 
  Attempting uninstall: opencv-contrib-python
    Found existing installation: opencv-contrib-python 4.1.2.30
    Uninstalling opencv-contrib-python-4.1.2.30:
      Successfully uninstalled opencv-contrib-python-4.1.2.30


In [ ]:
!pip uninstall opencv-python
!pip uninstall opencv-contrib-python

Found existing installation: opencv-python 4.1.2.30
Uninstalling opencv-python-4.1.2.30:
  Would remove:
    /usr/local/lib/python3.7/dist-packages/cv2/*
    /usr/local/lib/python3.7/dist-packages/opencv_python-4.1.2.30.dist-info/*
  Would not remove (might be manually added):
    /usr/local/lib/python3.7/dist-packages/cv2/config-3.7.py
    /usr/local/lib/python3.7/dist-packages/cv2/config.py
    /usr/local/lib/python3.7/dist-packages/cv2/gapi/__init__.py
    /usr/local/lib/python3.7/dist-packages/cv2/load_config_py2.py
    /usr/local/lib/python3.7/dist-packages/cv2/load_config_py3.py
    /usr/local/lib/python3.7/dist-packages/cv2/mat_wrapper/__init__.py
    /usr/local/lib/python3.7/dist-packages/cv2/misc/__init__.py
    /usr/local/lib/python3.7/dist-packages/cv2/misc/version.py
    /usr/local/lib/python3.7/dist-packages/cv2/utils/__init__.py
    /usr/local/lib/python3.7/dist-packages/cv2/version.py
Proceed (y/n)? y
  Successfully uninstalled opencv-python-4.1.2.30
Found existing insta

# Import lib

In [ ]:
import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# SIFT Implementation

In [ ]:
img = cv2.imread('cubes.jpg')
gray= cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

In [ ]:
sift = cv2.xfeatures2d.SIFT_create()
kp = sift.detect(gray,None)

In [ ]:
image = cv2.drawKeypoints(gray, kp, outImage=img, flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
cv2.imwrite('sift_keypoints.jpg',img)

True

In [ ]:
kp, des = sift.detectAndCompute(gray,None)

In [ ]:
!git clone https://github.com/Akhilesh64/Image-Classification-using-SIFT

Cloning into 'Image-Classification-using-SIFT'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 13 (delta 2), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (13/13), done.


In [ ]:
%cd /content/Image-Classification-using-SIFT

/content/Image-Classification-using-SIFT


In [ ]:
!wget https://github.com/myleott/mnist_png/raw/master/mnist_png.tar.gz

--2021-10-26 14:06:06--  https://github.com/myleott/mnist_png/raw/master/mnist_png.tar.gz
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/myleott/mnist_png/master/mnist_png.tar.gz [following]
--2021-10-26 14:06:07--  https://raw.githubusercontent.com/myleott/mnist_png/master/mnist_png.tar.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15683414 (15M) [application/octet-stream]
Saving to: ‘mnist_png.tar.gz’

mnist_png.tar.gz    100%[===================>]  14.96M  --.-KB/s    in 0.1s    

2021-10-26 14:06:07 (111 MB/s) - ‘mnist_png.tar.gz’ saved [15683414/15683414]



In [ ]:
!tar -xf mnist_png.tar.gz

In [ ]:
!python main.py


Calculating for a threshold of 5

Accuracy = 70.30277185501066
Time taken = 947.4690344333649 sec
Confusion matrix :
[[1001    4   21    6    1   33   46   16   57   13]
 [   3 1147   12    2   11    2    5   16    2    1]
 [  57    9  682   66   49   41   66  131   61   23]
 [  24    8   85  864   33   78   28   33   32    9]
 [   6    6   69   33  814   38   32   62   32   75]
 [  69    4   37   40   32  717   66   43   19   45]
 [  92   17   38   17   11   65  618   56   44  185]
 [  30   57  128   23   52   20   49  870   16    8]
 [  73    6   57   35   39   29   60    7  821   37]
 [  46    8   21   11   46   59  160   27   61  709]]

Calculating for a threshold of 10

Accuracy = 75.59061833688699
Time taken = 1135.1768279075623 sec
Confusion matrix :
[[1045    9   16    6    1   25   43   21   16   16]
 [   1 1186   12    1   10    4    6   27    1    2]
 [  34    6  772   38   30   38   23  122   45   20]
 [  12    4   78  900   20  107   12   29   28   22]
 [   6   11   51   